picture_types = ["*.png", "*.gif", "*.jpeg", "*.jpg"]
executable_types = ["*.exe", "*.com", "*.bat"]
video_types = ["*.mov", "*.avi", "*.mp4"]
audio_types = ["*.mp3", "*.wav"]
skipped_users = ["postgres"]
